/**
 * @module app/tools/llms-txt/page
 * llms.txt Generator — a free tool that generates an llms.txt file
 * for any employer. This is a viral acquisition tool:
 * - Genuinely useful (solves a real problem)
 * - Shareable (HR teams forward to dev teams)
 * - Captures intent (if you need this, you need Rankwell)
 *
 * llms.txt is the emerging standard for telling AI models
 * how to represent your organisation.
 */

"use client";

import { useState } from "react";
import Link from "next/link";
import {
  ArrowRight,
  Copy,
  Check,
  FileText,
  Download,
  Lightbulb,
  Zap,
} from "lucide-react";

import { Header } from "@/components/shared/header";
import { Footer } from "@/components/shared/footer";

/* ------------------------------------------------------------------ */
/* Generator logic                                                     */
/* ------------------------------------------------------------------ */

interface FormData {
  companyName: string;
  domain: string;
  industry: string;
  headquarters: string;
  founded: string;
  employees: string;
  description: string;
  mission: string;
  culture: string;
  benefits: string;
  salaryRange: string;
  remotePolicy: string;
  techStack: string;
  careersUrl: string;
  glassdoorUrl: string;
  linkedinUrl: string;
}

function generateLlmsTxt(data: FormData): string {
  const lines: string[] = [];

  lines.push(`# ${data.companyName}`);
  lines.push("");
  lines.push(`> ${data.description || `${data.companyName} is a ${data.industry} company based in ${data.headquarters}.`}`);
  lines.push("");

  lines.push("## Company Overview");
  lines.push("");
  if (data.domain) lines.push(`- Website: https://${data.domain.replace(/^https?:\/\//, "")}`);
  if (data.industry) lines.push(`- Industry: ${data.industry}`);
  if (data.headquarters) lines.push(`- Headquarters: ${data.headquarters}`);
  if (data.founded) lines.push(`- Founded: ${data.founded}`);
  if (data.employees) lines.push(`- Employees: ${data.employees}`);
  lines.push("");

  if (data.mission) {
    lines.push("## Mission");
    lines.push("");
    lines.push(data.mission);
    lines.push("");
  }

  lines.push("## Working at " + data.companyName);
  lines.push("");
  if (data.culture) {
    lines.push("### Culture");
    lines.push("");
    lines.push(data.culture);
    lines.push("");
  }
  if (data.remotePolicy) {
    lines.push("### Remote & Flexibility");
    lines.push("");
    lines.push(data.remotePolicy);
    lines.push("");
  }
  if (data.benefits) {
    lines.push("### Benefits");
    lines.push("");
    lines.push(data.benefits);
    lines.push("");
  }
  if (data.salaryRange) {
    lines.push("### Compensation");
    lines.push("");
    lines.push(data.salaryRange);
    lines.push("");
  }
  if (data.techStack) {
    lines.push("### Technology");
    lines.push("");
    lines.push(data.techStack);
    lines.push("");
  }

  lines.push("## Links");
  lines.push("");
  if (data.careersUrl) lines.push(`- Careers: ${data.careersUrl}`);
  if (data.linkedinUrl) lines.push(`- LinkedIn: ${data.linkedinUrl}`);
  if (data.glassdoorUrl) lines.push(`- Glassdoor: ${data.glassdoorUrl}`);
  lines.push("");

  lines.push("---");
  lines.push("");
  lines.push(`*This file was generated by Rankwell (https://rankwell.io/tools/llms-txt).*`);
  lines.push(`*Last updated: ${new Date().toISOString().split("T")[0]}*`);

  return lines.join("\n");
}

/* ------------------------------------------------------------------ */
/* Page                                                                */
/* ------------------------------------------------------------------ */

export default function LlmsTxtGenerator() {
  const [formData, setFormData] = useState<FormData>({
    companyName: "",
    domain: "",
    industry: "",
    headquarters: "",
    founded: "",
    employees: "",
    description: "",
    mission: "",
    culture: "",
    benefits: "",
    salaryRange: "",
    remotePolicy: "",
    techStack: "",
    careersUrl: "",
    glassdoorUrl: "",
    linkedinUrl: "",
  });
  const [generated, setGenerated] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const handleChange = (field: keyof FormData, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  const handleGenerate = () => {
    if (!formData.companyName) return;
    setGenerated(generateLlmsTxt(formData));
  };

  const handleCopy = async () => {
    if (!generated) return;
    await navigator.clipboard.writeText(generated);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    if (!generated) return;
    const blob = new Blob([generated], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "llms.txt";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <Header />

      <main>
        {/* ── Hero ─────────────────────────── */}
        <section className="bg-white border-b border-slate-200 relative overflow-hidden">
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_1px_1px,_var(--neutral-200)_1px,_transparent_0)] [background-size:32px_32px] opacity-30" />
          <div className="absolute inset-0 bg-gradient-to-b from-white to-transparent" />
          <div className="relative mx-auto max-w-[1200px] px-6 lg:px-12 py-16 lg:py-20">
            <div className="flex items-start gap-3 mb-5">
              <FileText className="h-6 w-6 text-brand-accent mt-0.5" />
              <p className="overline">Free Tool</p>
            </div>
            <h1 className="text-3xl lg:text-4xl xl:text-5xl font-bold text-slate-900 tracking-tight max-w-2xl">
              llms.txt Generator
            </h1>
            <p className="mt-4 text-lg text-slate-500 max-w-2xl leading-relaxed">
              Generate an{" "}
              <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded font-mono">
                llms.txt
              </code>{" "}
              file for your company — the emerging standard for telling AI
              models how to accurately represent your organisation. Place it at
              your domain root and AI will use it as a source of truth.
            </p>

            {/* Why it matters */}
            <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-4">
              {[
                {
                  icon: <Lightbulb className="h-5 w-5 text-amber-500" />,
                  title: "AI reads it",
                  desc: "LLMs check for llms.txt when answering questions about your company.",
                },
                {
                  icon: <Zap className="h-5 w-5 text-teal-500" />,
                  title: "You control the narrative",
                  desc: "Define your culture, benefits, and salary data — in your own words.",
                },
                {
                  icon: <FileText className="h-5 w-5 text-blue-500" />,
                  title: "5 minutes to set up",
                  desc: "Fill in the form, download the file, upload to your domain root.",
                },
              ].map((item, i) => (
                <div
                  key={i}
                  className="rounded-xl border border-slate-200 bg-white p-4"
                >
                  {item.icon}
                  <p className="mt-2 text-sm font-semibold text-slate-900">
                    {item.title}
                  </p>
                  <p className="mt-1 text-xs text-slate-500">{item.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ── Generator ────────────────────── */}
        <section className="py-12 lg:py-16">
          <div className="mx-auto max-w-[1200px] px-6 lg:px-12">
            <div className="grid lg:grid-cols-2 gap-8">
              {/* Form */}
              <div className="space-y-6">
                <h2 className="text-xl font-bold text-slate-900">
                  Your company details
                </h2>

                {/* Required */}
                <div className="space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-1">
                      Company name *
                    </label>
                    <input
                      type="text"
                      value={formData.companyName}
                      onChange={(e) =>
                        handleChange("companyName", e.target.value)
                      }
                      placeholder="e.g. Monzo"
                      className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                    />
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-neutral-700 mb-1">
                        Domain
                      </label>
                      <input
                        type="text"
                        value={formData.domain}
                        onChange={(e) =>
                          handleChange("domain", e.target.value)
                        }
                        placeholder="monzo.com"
                        className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-neutral-700 mb-1">
                        Industry
                      </label>
                      <input
                        type="text"
                        value={formData.industry}
                        onChange={(e) =>
                          handleChange("industry", e.target.value)
                        }
                        placeholder="Fintech"
                        className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                      />
                    </div>
                  </div>
                  <div className="grid grid-cols-3 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-neutral-700 mb-1">
                        Headquarters
                      </label>
                      <input
                        type="text"
                        value={formData.headquarters}
                        onChange={(e) =>
                          handleChange("headquarters", e.target.value)
                        }
                        placeholder="London, UK"
                        className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-neutral-700 mb-1">
                        Founded
                      </label>
                      <input
                        type="text"
                        value={formData.founded}
                        onChange={(e) =>
                          handleChange("founded", e.target.value)
                        }
                        placeholder="2015"
                        className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-neutral-700 mb-1">
                        Employees
                      </label>
                      <input
                        type="text"
                        value={formData.employees}
                        onChange={(e) =>
                          handleChange("employees", e.target.value)
                        }
                        placeholder="3,000+"
                        className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                      />
                    </div>
                  </div>
                </div>

                {/* Employer brand fields */}
                <div className="space-y-4">
                  <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider">
                    Employer Brand
                  </h3>
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-1">
                      Company description
                    </label>
                    <textarea
                      value={formData.description}
                      onChange={(e) =>
                        handleChange("description", e.target.value)
                      }
                      placeholder="One paragraph describing what your company does..."
                      rows={2}
                      className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-1">
                      Mission / values
                    </label>
                    <textarea
                      value={formData.mission}
                      onChange={(e) =>
                        handleChange("mission", e.target.value)
                      }
                      placeholder="What drives your company..."
                      rows={2}
                      className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-1">
                      Culture
                    </label>
                    <textarea
                      value={formData.culture}
                      onChange={(e) =>
                        handleChange("culture", e.target.value)
                      }
                      placeholder="Describe your work culture, team dynamics, values in practice..."
                      rows={2}
                      className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-1">
                      Remote / flexibility policy
                    </label>
                    <input
                      type="text"
                      value={formData.remotePolicy}
                      onChange={(e) =>
                        handleChange("remotePolicy", e.target.value)
                      }
                      placeholder="e.g. Hybrid (3 days office, 2 remote). Flexible hours."
                      className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-1">
                      Key benefits
                    </label>
                    <textarea
                      value={formData.benefits}
                      onChange={(e) =>
                        handleChange("benefits", e.target.value)
                      }
                      placeholder="List key benefits: pension, health, equity, parental leave..."
                      rows={2}
                      className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-1">
                      Salary ranges
                    </label>
                    <input
                      type="text"
                      value={formData.salaryRange}
                      onChange={(e) =>
                        handleChange("salaryRange", e.target.value)
                      }
                      placeholder="e.g. Engineering: £55K-120K. Product: £60K-100K."
                      className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-neutral-700 mb-1">
                      Tech stack (optional)
                    </label>
                    <input
                      type="text"
                      value={formData.techStack}
                      onChange={(e) =>
                        handleChange("techStack", e.target.value)
                      }
                      placeholder="e.g. TypeScript, React, Go, Kubernetes, AWS"
                      className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                    />
                  </div>
                </div>

                {/* Links */}
                <div className="space-y-4">
                  <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider">
                    Links
                  </h3>
                  <div className="grid grid-cols-1 gap-3">
                    <input
                      type="text"
                      value={formData.careersUrl}
                      onChange={(e) =>
                        handleChange("careersUrl", e.target.value)
                      }
                      placeholder="Careers page URL"
                      className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                    />
                    <input
                      type="text"
                      value={formData.linkedinUrl}
                      onChange={(e) =>
                        handleChange("linkedinUrl", e.target.value)
                      }
                      placeholder="LinkedIn company URL"
                      className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                    />
                    <input
                      type="text"
                      value={formData.glassdoorUrl}
                      onChange={(e) =>
                        handleChange("glassdoorUrl", e.target.value)
                      }
                      placeholder="Glassdoor profile URL"
                      className="w-full rounded-xl border border-slate-200 px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-neutral-950/10 focus:border-neutral-300"
                    />
                  </div>
                </div>

                <button
                  onClick={handleGenerate}
                  disabled={!formData.companyName}
                  className="w-full rounded-xl bg-teal-600 px-6 py-3 text-sm font-semibold text-white hover:bg-teal-700 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
                >
                  Generate llms.txt
                </button>
              </div>

              {/* Output */}
              <div>
                <div className="sticky top-8">
                  <h2 className="text-xl font-bold text-slate-900 mb-4">
                    Your llms.txt file
                  </h2>

                  {generated ? (
                    <div className="rounded-2xl border border-slate-200 bg-white overflow-hidden">
                      <div className="flex items-center justify-between px-4 py-3 border-b border-neutral-100 bg-slate-50/80">
                        <span className="text-xs font-mono text-slate-500">
                          llms.txt
                        </span>
                        <div className="flex items-center gap-2">
                          <button
                            onClick={handleCopy}
                            className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-600 hover:text-slate-900 transition-colors"
                          >
                            {copied ? (
                              <Check className="h-3.5 w-3.5 text-teal-500" />
                            ) : (
                              <Copy className="h-3.5 w-3.5" />
                            )}
                            {copied ? "Copied" : "Copy"}
                          </button>
                          <button
                            onClick={handleDownload}
                            className="inline-flex items-center gap-1.5 text-xs font-medium text-slate-600 hover:text-slate-900 transition-colors"
                          >
                            <Download className="h-3.5 w-3.5" />
                            Download
                          </button>
                        </div>
                      </div>
                      <pre className="p-4 text-xs font-mono text-neutral-700 whitespace-pre-wrap overflow-auto max-h-[600px] leading-relaxed">
                        {generated}
                      </pre>
                    </div>
                  ) : (
                    <div className="rounded-2xl border border-dashed border-neutral-300 bg-slate-50/50 p-12 text-center">
                      <FileText className="h-10 w-10 text-slate-300 mx-auto mb-3" />
                      <p className="text-sm text-slate-500">
                        Fill in the form and click Generate to create your
                        llms.txt file.
                      </p>
                    </div>
                  )}

                  {/* Instructions */}
                  {generated && (
                    <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-5">
                      <h3 className="text-sm font-semibold text-slate-900 mb-3">
                        How to install
                      </h3>
                      <ol className="space-y-2 text-sm text-slate-600">
                        <li className="flex gap-2">
                          <span className="font-semibold text-slate-900">
                            1.
                          </span>
                          Download or copy the file above
                        </li>
                        <li className="flex gap-2">
                          <span className="font-semibold text-slate-900">
                            2.
                          </span>
                          Upload to your website root:{" "}
                          <code className="text-xs bg-slate-100 px-1 rounded">
                            {formData.domain || "yourdomain.com"}/llms.txt
                          </code>
                        </li>
                        <li className="flex gap-2">
                          <span className="font-semibold text-slate-900">
                            3.
                          </span>
                          Run a{" "}
                          <Link
                            href="/#audit"
                            className="text-brand-accent hover:underline"
                          >
                            free audit
                          </Link>{" "}
                          to verify AI can read it
                        </li>
                      </ol>
                      <div className="mt-4 p-3 rounded-xl bg-teal-50 border border-teal-200">
                        <p className="text-xs text-teal-700">
                          <strong>Tip:</strong> Companies with llms.txt score
                          15-25 points higher on the AI Employer Index. It&apos;s
                          the single biggest quick win.
                        </p>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ── CTA ──────────────────────────── */}
        <section className="py-12 border-t border-slate-200 bg-white">
          <div className="mx-auto max-w-2xl px-6 text-center">
            <h2 className="text-xl font-bold text-slate-900 mb-2">
              Want to go further?
            </h2>
            <p className="text-sm text-slate-500 mb-6">
              llms.txt is step one. A full Rankwell audit checks 50+ signals
              across 6 AI models and gives you a complete action plan.
            </p>
            <Link
              href="/#audit"
              className="inline-flex items-center justify-center rounded-xl bg-teal-600 px-6 py-3 text-sm font-semibold text-white hover:bg-teal-700 transition-colors"
            >
              Run your free audit
              <ArrowRight className="ml-1.5 h-3.5 w-3.5" />
            </Link>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
